### ISSUE TITLE
Reset button on #annotate does not work when logged in

### ISSUE THREAD

**Issue by entrez** [nethackathon/nethackathon-web#1]
The `DELETE` request for `resetOnline()` is apparently disallowed by CORS (`api.nethackathon.org` responds with `Access-Control-Allow-Methods: GET,POST`) so is not made when I press the 'reset' button.

If I make the `DELETE` request from curl anyway, it returns a 500 status code and an error page with this backtrace:

```
Error: Subquery returns more than 1 row
    at PromisePool.execute (/home/ubuntu/nethackathon-node/node_modules/mysql2/promise.js:359:22)
    at Object.query (/home/ubuntu/nethackathon-node/src/services/db.service.js:7:38)
    at Object.deleteData (/home/ubuntu/nethackathon-node/src/services/annotate.service.js:24:12)
    at deleteData (/home/ubuntu/nethackathon-node/src/controllers/annotate.controller.js:23:36)
    at Layer.handle [as handle_request] (/home/ubuntu/nethackathon-node/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/nethackathon-node/node_modules/express/lib/router/route.js:137:13)
    at verifyToken (/home/ubuntu/nethackathon-node/src/middleware/auth.js:17:12)
    at Layer.handle [as handle_request] (/home/ubuntu/nethackathon-node/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/nethackathon-node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ubuntu/nethackathon-node/node_modules/express/lib/router/route.js:112:3)
```

I wasn't sure whether it was more appropriate to open this here or at the nethackathon-node repo -- probably the latter would have been better, thinking about it now.  Sorry if I chose wrong!

**Comment by disperse** [comment]
Thank you for the detailed bug report! 

I was able to fix this issue by modifying the CORS config, fix here:
https://github.com/nethackathon/nethackathon-node/commit/175292bd303afff431bb0f74c5ce0255a4f3cb42

**Comment by entrez** [comment]
Thanks for checking this out, @disperse.  I don't seem to get the CORS issue any more, but it still isn't working for me.  Looking at the "network" tab under developer tools, in response to the DELETE request the API returns 403 forbidden with response contents "JWT token not found".  If I make the request directly from curl I get the same thing as before ("Error: subquery returns more than 1 row").

**Comment by disperse** [comment]
What is the username you're logging in with?

My suspicion is this is related to another issue which is allowing multiple users to be created with the same username.

**Comment by entrez** [comment]
Oh, interesting.  It does seem plausible that I might have created a duplicate account without realizing it.  The username I'm using on there is "qt".

**Comment by disperse** [comment]
Yeah, there are three qt rows in the user database. Let me fix the underlying issue and then I'll clean up the data.

**Comment by entrez** [comment]
Oh, perfect -- I guess I either previously tested whether I already had an account by trying to register a new one and seeing if it blocked me, or confused login and registration. :P

**Comment by disperse** [comment]
There was a bug that let you register the same username multiple times, also the UI was confusing. I fixed the bug and slightly improved the UI to make it clearer when you're signing up or logging in.

I'm not 100% certain this will solve your problem but can you try logging out and logging in again?

**Comment by entrez** [comment]
Now I can't log in, I guess the password to the account I have been using and whichever one has been retained are different.  Or did you delete all the accounts and I should reregister?

**Comment by disperse** [comment]
A side-effect of allowing people to double-register was they were able to change their password (really, have multiple passwords). I need to add a mechanism for people to request password resets. In the meantime, your password is something that you'd be happy to see if you were looking for, maybe, a chance to get magic resistance.

**Comment by entrez** [comment]
Thanks.  I think there's some new kind of problem now...  When I log in with that it prints a long alphanumeric string where it would print "invalid credentials" if I entered the wrong password.  It's almost like it's returning some kind of token to say "here's the authorization key" but it's being printed to the screen instead of stored and used?  If that's a unique problem to my account I can always register a new one...

**Comment by disperse** [comment]
I made some front-end updates as well, so you'll have to hold Shift and press the reload button to get the latest client. That /should/ fix it.

**Comment by entrez** [comment]
Thanks so much for all the effort, that works now -- as does the reset button!  (It does seem to delete the entire list of intrinsics, not just clear the check marks, but that's fixed by reloading the page so not a big deal.)
